### ISSUE TITLE
Replace rsync cron job with a more robust decentralized solution

### ISSUE THREAD

**Issue by carnesen** [bitseed-org/bitcoin-box#12]
I'm skeptical of the cron job that takes the node down for a half hour every day to make a local backup of the block chain. That's a lot of downtime to protect against what, in my experience, is a rare event (database corruption), especially when there's already another backup mechanism in place (resync'ing the block chain from the network). Does it really take "weeks" to resync the block chain from scratch on the Bitseed? With headers-first sync starting in v0.10, I've seen a sync complete in just a few hours on a beefy VM.

**Comment by jfeldis** [comment]
rsync of the live db sometimes creates a backup that will be rejected by bitcoid since files may be changes while being copied.  I have tried and it often makes a useless backup.  So we have to stop bitcoin to make a clean backup.   The index db is quite sensitive to any disturbance.  Battery backup is an option we are looking at.

The device processes about 5 blocks per minute at heights above ~200K  (early blocks are much faster). I have measured this.   The backup could be reduced to once per month, which the device would need about 14 hours to catch up, or turned off altogether if you dont mind the risk.  The device will respond to RPC and relay transactions after about 15 minutes, but wont have indexed recent blocks.   It is a low cost, low power device, with the intent to keep the cost of running a node very low, and disk space is cheap

We are using v0.10 on the current device and the default indexing is not fast..  Perhaps there is a setting to enable headers first?   It is not the download that takes time, but rather the building of the index.   As pruning is stabilized we will evaluate that as well (although a full node is our goal here)

**Comment by carnesen** [comment]
Thank you for the explanation. At 5 blocks per minute, it really would take weeks to resync from scratch! Headers-first is the default in v0.10. Its advantage is that it parallelizes the process of verifying blocks, but I suppose that doesn't help in this case. If a month-old backup only takes 14 hours to recover from, I tend to think that a better balance than losing a half-hour of service per day for daily backups.

**Comment by carnesen** [comment]
The Bitseed servers (both the little boxes all over the world as well as the company's servers) could seed periodic snapshots of pre-indexed bitcoind data as torrents.

**Comment by jfeldis** [comment]
yes, I have thought of the idea that the boxes could torrent pre-indexed backups to each other.  One issue to consider is the integrity of those backups.  I assume that having devices maintain their own indexes prevents a potential avenue for double spend attacks.  What if a hacked index is distributed by a maliciously modified node?

**Comment by carnesen** [comment]
I'm not 100%, but I was supposing that Bitseed the organization could seed the network with _signed_ pre-indexed data. I might download it from one of my peers, but I could verify that the signature is correct. The user already has to trust that Bitseed didn't put malicious data onto the device. I think this would involve a similar level of trust.
