### ISSUE TITLE
Add ability to set bandwidth throttling in Admin panel

### ISSUE THREAD

**Issue by jlopp** [bitseed-org/bitcoin-box#7]
I was going to create this issue on the BitcoinNodeAdmin repo but it looks like GitHub issues haven't been enabled on it.

I think it would be very helpful to provide bandwidth throttling built into the admin web interface, which should be doable via the QoS script already provided by the Bitcoin Core devs.

Basically I envision a simple form where the user can submit an integer for how many kilobits / kilobytes per second they want to set the max bandwidth usage to be. That form submission should kick off the execution of this script, dynamically setting the LIMIT variable: https://github.com/bitcoin/bitcoin/blob/master/contrib/qos/tc.sh

**Comment by jfeldis** [comment]
I think the bandwidth use of bitcoind is governed by 
a) the size of the blocks on the network
b) the rate of transaction messages on the network
c) the number of connections a node maintains to other nodes/clients

(a) and (b) are properties of the network and an effective node must handle that data with low latency

(c) the maximum number of connections the node will accept can be limited by adding maxconnections=<n> to bitcoin.conf.     

I think (c) should be powerful because 20 connections would 2x the bandwidth of 10 connections, etc

I imagine port 8333 bandwidth limits might smooth out peak bandwidth usage by slowing the transfer of large blocks and transaction data, but that essentially adds latency when the network gets busy. and it cannot make the node use less data per connection and still do its job.  At what point is a node too slow to be a benefit to the network?  Am I missing something?

My guess is that the best approach is to limit the number of connections maxconnections=(n) to a number that can be handled without adding latency or causing problems with other network services.

Is the Qos https://github.com/bitcoin/bitcoin/blob/master/contrib/qos/tc.sh  perhaps a special case situation where you want to use one node as a "gateway" to other nodes on an internal network?

**Comment by jlopp** [comment]
You're missing D) sending large numbers of historical blocks to nodes that have just joined the network and are syncing to catch up to the tip of the block chain. This is where the upstream bandwidth spikes come from and can easily max out a residential internet connection.

Trying to limit bandwidth usage by limiting the number of connections is a rough way of doing so and still doesn't prevent D from occurring. I don't recommend trying to find an optimal number of connections because it will vary from user to user and Bitcoin Core already does a decent job of managing peer connections.

**Comment by jlopp** [comment]
FWIW, my node analysis has shown that even well connected nodes with 100+ peers only use on average 5 KB/S downstream and < 100 KB/S upstream. Though I often see spikes of several MB/S when a peer requests a large chunk of historical blocks. I'd recommend telling users to dedicate at least 50 KB/S of upstream bandwidth.

**Comment by jfeldis** [comment]
Excellent point.  I had not thought of (D), and that might get to be more of an issue over time and as pruned nodes come online.  I will try out the QoS script.

**Comment by jlopp** [comment]
Good news, it looks like Addy at Bitnodes has a script that you may be able to use: https://github.com/ayeowch/bitnodes-hardware/blob/master/bandwidth_control.sh

**Comment by john-light** [comment]
We have enabled this in the Bitseed Web UI:

https://github.com/bitseed-org/bitseed-web-ui-2/blob/6ee1f0705bf9997fa731c3ec117b3563cde76afe/html/html/dev_bcupdate_page.php#L88
