### ISSUE TITLE
txindex should be enabled by default

### ISSUE THREAD

**Issue by carnesen** [bitseed-org/bitcoin-box#9]
Many services built on top of Bitcoin Core require its transaction index, which is disabled by default. The Bitseed Server should have txindex=1 in bitcoin.conf.

**Comment by jfeldis** [comment]
Yes.  This is the plan for the next version.  txindex increases the storage requirement to about 45GB currently.  Since we keep a backup, 90GB is used.  I want to test for a while to assure stability.  If you add txindex=1 to bitcoin.conf in the device, it will re-index which may take a week or more to complete.

**Comment by jfeldis** [comment]
txindex is enabled in V2  v0.2
